// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8osZhuJoeQgTI9EeKRaxMLMdoxZGNjkY',
    appId: '1:639564714936:web:5a29ddd46551b0bf5f754d',
    messagingSenderId: '639564714936',
    projectId: 'social1-59810',
    authDomain: 'social1-59810.firebaseapp.com',
    storageBucket: 'social1-59810.firebasestorage.app',
    measurementId: 'G-LRHN9VPB9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHWcatLg0A5YKJyP9DpvUaZ7F-GXeYXMY',
    appId: '1:639564714936:android:de088009154724c95f754d',
    messagingSenderId: '639564714936',
    projectId: 'social1-59810',
    storageBucket: 'social1-59810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaFF8teT6ua0sKTXLmX8uUqP15tSb90q0',
    appId: '1:639564714936:ios:c3ad0f1abfa5d3875f754d',
    messagingSenderId: '639564714936',
    projectId: 'social1-59810',
    storageBucket: 'social1-59810.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaFF8teT6ua0sKTXLmX8uUqP15tSb90q0',
    appId: '1:639564714936:ios:c3ad0f1abfa5d3875f754d',
    messagingSenderId: '639564714936',
    projectId: 'social1-59810',
    storageBucket: 'social1-59810.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8osZhuJoeQgTI9EeKRaxMLMdoxZGNjkY',
    appId: '1:639564714936:web:1baf7cf1d3efea8f5f754d',
    messagingSenderId: '639564714936',
    projectId: 'social1-59810',
    authDomain: 'social1-59810.firebaseapp.com',
    storageBucket: 'social1-59810.firebasestorage.app',
    measurementId: 'G-MWSBKGL635',
  );
}
